### ISSUE TITLE
on-prem: error resolving minio's hostname in backups logs 

### ISSUE THREAD

**Issue by ralgozino** [sighupio/fury-kubernetes-dr#59]
If you check the logs for a `test` backup in COMPLETED status with a command like:

```shell
velero backup logs -n kube-system test
```

You may see an error saying that the resolution of the internal minio's hostname failed:

```log
An error occurred: Get "http://minio-0.minio.kube-system.svc.cluster.local:9000/kube-system/backups/test/test-logs.gz?X-Amz-Algorithm=...": dial tcp: lookup minio-0.minio.kube-system.svc.cluster.local on <YOUR-DNS-SERVER-IP>:53: no such host
```

But this error is misleading. If you go to minio's UI, you'll see that the backups are there.

Could be related:

- vmware-tanzu/velero#2590

**Comment by ralgozino** [comment]
The thing is... the error you are seeing is from `velero` CLI itself and not the logs of the backup. The CLI tries to connect to the bucket (minio) to download the logs and it fails because the hostname is internal to the cluster and your PC can't reach it.

A workaround is to:
1. kubectl port-forward minio to your PC to something like localhost:9000
2. add an entry to your `/etc/hosts` file pointing minio's hostname to 127.0.0.1:9000

`velero backup logs` should work now.

Don't forget to delete the entry from your `/etc/hosts` afterwards.

**Comment by antoweb** [comment]
Hello. Ok but in my case i have a service on my PC already listening to 9000 (Zscaler). Is possible to use anorher Port o have anorher workaroubd?

**Comment by antoweb** [comment]
Maybe change the Port that the cli use?

**Comment by ralgozino** [comment]
Hi @antoweb,

`kubectl port-forward` lets you choose the local port, you can do something like:

```bash
kubectl port-forward -n kube-system minio-o <THE PORT YOU WANT>:9000
```

You can also change the local IP and other parameters, see `kubectl port-forward --help` for more details.

**Comment by antoweb** [comment]
> Hi @antoweb,
> 
> `kubectl port-forward` lets you choose the local port, you can do something like:
> 
> ```shell
> kubectl port-forward -n kube-system minio-o <THE PORT YOU WANT>:9000
> ```
> 
> You can also change the local IP and other parameters, see `kubectl port-forward --help` for more details.

Hi @ralgozino i know that i can use another port with port forward but velero cli try to use always the 9000, so the command velero describe backup wont work anyways

**Comment by ralgozino** [comment]
One workaround is to run the velero cli form a pod inside the cluster, so it reach the internal service.
